---
title: "RDeber"
author: "Sebastian Neto"
date: "25/2/2022"
output: html_document
---

```{r Setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Tarea 1:
* Ejercicio 1

```{r Ejerc1}
# Ejercicio 1:

ciudad <- "Tena"

print(ciudad)

```

* Ejercicio 2:


```{r Ejerc2}

# Ejercicio2:

pais_andes <- c("Argentina", "Ecuador", "Bolivia", "Chile", "Colombia", "Perú", "Venezuela")

print(pais_andes)
```

* Ejercicio 3:

```{r Ejerc3}

# Ejercicio3:

Datos_trabajadores = data.frame(num_Trabajador = paste0("Trb", 1:12), Nombre = c("Sebastian", "Anderson", "Rosa", "Mariana", "Paola", "María", "Ruth", "Mateo", "Antonella", "Teresa", "Juan", "Daniela"), Apellido = c("Neto", "Yumbo", "Briñoles", "Silva", "Calderón", "Minango", "Guevara", "Benalcazar", "Ortiz", "Vélez", "Villacrés", "Benavides"), Salario = sample(800.05:1200.75, 12, replace = TRUE), Num_Dias_vacaciones =sample(10:30, 12, replace = TRUE) )

Datos_trabajadores
```

* Ejecicio 4

```{r Ejerc41}

# Ejercicio 4.1:

# Selección del dataset "DNase"
?DNase

print(head(DNase, 4))

concentracion = subset(DNase, conc >= 0.1 & conc <= 0.2)

print(concentracion)

```
```{r Ejerc42}

# Ejercicio 4.2:

# Selección del dataset "DNase"
?DNase

concentracion2 = subset(DNase, Run != 2 & conc > 0.2 & density <= 1.0)

print(concentracion2)

```

